/**
 * projects.js — Canonical project data sourced from official brochures.
 * NOTE: Only safe single-codepoint emoji used (no variation selectors).
 */

export const ACTIVE_PROJECTS = [
  {
    id:          'anjana',
    name:        'Anjana Paradise',
    loc:         'Paritala, Near Amaravati',
    fullAddress: 'Paritala Village, Krishna District, Andhra Pradesh 521180',
    accentClass: 'accentGold',
    heroImage:   '/Anjana_Paradise_Paritala_Home.png',
    available:   14,
    total:       242,      // confirmed from Paritala layout plan (242 plots)
    starting:    'Rs.24.8L',
    pricing: {
      east:    { base: 13000, dev: 1000, label: 'Rs.13,000 + Rs.1,000 Dev. Charges' },
      west:    { base: 12500, dev: 1000, label: 'Rs.12,500 + Rs.1,000 Dev. Charges' },
      corners: [
        { type: 'North-East Corner', extra: 1000, label: 'Rs.1,000/sq.yd extra' },
        { type: 'Other Corners',     extra: 500,  label: 'Rs.500/sq.yd extra'   },
      ],
      note: 'All prices per sq. yard. Corner charges additional.',
    },
    tag:         'Featured',
    status:      'APCRDA LP No: 35/2025 | AP RERA P06060125894',
    // Source: paritala_plot_dimensions.xlsx (Paritala Plan-22.pdf, 242 plots)
    facings: { east: 113, eastNorth: 1, eastWest: 2, west: 122, westNorth: 1, southEast: 1, southWest: 2 },
    approvals:   ['CRDA Proposed Layout', 'AP RERA Registered', '100% Clear Title', '100% Vaastu'],
    highlights: [
      'Adjacent to National Highway (NH-16)',
      '8 km from Amaravati — New State Capital',
      'Govt. Proposed Railway Connectivity to Paritala',
      'Proposed Logistic Hub in Paritala',
      'Near Engineering Colleges (Amrita Sai, MVR, MIC)',
      'Close to Nimra Medical College',
      'Near Mulapadu International Cricket Stadium',
      'Proposed Cine Studio near Nandigama',
    ],
    description: "Premium open plots in Paritala — adjacent to NH-16, just 8 km from Amaravati, the new capital of Andhra Pradesh. CRDA Proposed Layout with 100% clear title, avenue-lined roads, 24/7 water pipeline and overhead electricity on every plot. Ready for immediate construction.",
    amenities: [
      { tab: 'INFRA',     icon: '🏛', label: 'Architecturally Imposing Grand Entrance Arch' },
      { tab: 'INFRA',     icon: '🛣', label: 'Avenue Plantation on Both Sides of Roads'     },
      { tab: 'INFRA',     icon: '💧', label: 'Overhead Tank — Pipeline to Every Plot'       },
      { tab: 'INFRA',     icon: '💡', label: 'Overhead Electricity Lines'                   },
      { tab: 'INFRA',     icon: '🔒', label: 'Security Arch with CCTV Surveillance'         },
      { tab: 'INFRA',     icon: '📋', label: 'Name & Number Display Board per Plot'         },
      { tab: 'LIFESTYLE', icon: '🏃', label: 'Jogging Track Around Central Garden'          },
      { tab: 'LIFESTYLE', icon: '🌳', label: "Children's Tot Lot & Green Equipped Parks"    },
      { tab: 'LIFESTYLE', icon: '✅', label: '100% Vaastu Compliant Layout'                 },
      { tab: 'LIFESTYLE', icon: '🏦', label: 'Housing Loans Available Through Banks'        },
      { tab: 'INFRA',     icon: '📐', label: 'CRDA Proposed Layout — Ready for Construction'},
      { tab: 'UTILITIES', icon: '🚰', label: 'Ample Water Availability Round the Clock'     },
      { tab: 'UTILITIES', icon: '⚡', label: 'Designed LED Street Lights'                   },
      { tab: 'UTILITIES', icon: '🏊', label: 'Drainage System'                              },
      { tab: 'LIFESTYLE', icon: '🙏', label: 'Hanuman Temple — Just Minutes Away'           },
    ],
    gallery: [
      { label: 'Grand Entrance Arch',      icon: '🏛' },
      { label: 'Avenue Lined Roads',        icon: '🛣' },
      { label: "Children's Park",           icon: '🌳' },
      { label: 'Jogging Track',             icon: '🏃' },
      { label: 'Plot Layout Overview',      icon: '🏞' },
      { label: 'Overhead Tank & Pipeline',  icon: '💧' },
    ],
    videos: [
      { id: '55zBpY_j-lo', type: 'youtube', title: 'Anjana Paradise — Project Overview', subtitle: 'Full property walkthrough & amenities' },
    ],
    distances: [
      { icon: '🏛', name: 'Amaravati Capital',      subtitle: 'New AP State Capital',         distance: '8 km'  },
      { icon: '🛣', name: 'NH-16 National Highway', subtitle: 'Adjacent — direct access',     distance: '0 km'  },
      { icon: '🎓', name: 'Engineering Colleges',   subtitle: 'Amrita Sai, MVR, MIC College', distance: '5 km'  },
      { icon: '🏥', name: 'Nimra Medical College',  subtitle: 'Healthcare hub',               distance: '7 km'  },
      { icon: '🏏', name: 'Mulapadu Stadium',       subtitle: 'International Cricket',        distance: '6 km'  },
      { icon: '✈', name: 'Vijayawada Airport',      subtitle: 'Air connectivity',             distance: '22 km' },
      { icon: '🙏', name: 'Hanuman Temple',         subtitle: 'Shri Paritala Hanuman Temple', distance: '1 km'  },
    ],
    mapEmbedUrl: 'https://maps.google.com/maps?q=Paritala,Andhra+Pradesh,India&t=k&z=14&ie=UTF8&iwloc=&output=embed',
    mapOpenUrl:  'https://maps.google.com/?q=Paritala,Krishna+District,Andhra+Pradesh',
    contact: { phone: '+91 99487 09041', whatsapp: '919948709041', email: 'msnraoooo@gmail.com', address: 'Paritala, Krishna District, AP 521180', website: 'www.chaturbhujaplots.in' },
  },

  {
    id:          'trimbak',
    name:        'Trimbak Oaks',
    loc:         'Penamaluru, Near Vijayawada',
    fullAddress: 'Penamaluru, Krishna District, Andhra Pradesh',
    accentClass: 'accentGreen',
    heroImage:   '/All_Ready_To_Buy_Ventures.png',
    available:   0,
    total:       null,
    starting:    'Rs.57L',
    pricing: {
      east:    { base: 29000, dev: 1000, label: 'Rs.29,000 + Rs.1,000 Dev. Charges' },
      west:    { base: 28500, dev: 1000, label: 'Rs.28,500 + Rs.1,000 Dev. Charges' },
      corners: [
        { type: 'North-East Corner', extra: 1500, label: 'Rs.1,500/sq.yd extra' },
        { type: 'Other Corners',     extra: 1000, label: 'Rs.1,000/sq.yd extra' },
      ],
      booking:   { amount: 200000, label: 'Rs.2,00,000/- Booking Amount' },
      agreement: { fraction: '1/3', label: '1/3rd at Agreement' },
      note: 'All prices per sq. yard. Corner charges additional.',
    },
    tag:         'Upcoming',
    status:      'Details Coming Soon',
    upcoming:    true,
    facings:     {},
    approvals:   ['CRDA Approved', 'RERA Registered', '100% Clear Title'],
    highlights: [
      '5 km from Vijayawada City Centre',
      'NH-16 Direct Access',
      'Gated Community with 24/7 Security',
      'Water & Electricity on every plot',
      'Ready for immediate construction',
      'Housing loans available',
    ],
    description: 'Gated community plots offering excellent connectivity to Vijayawada city via NH-16. CRDA approved with all modern infrastructure — water, electricity, drainage and security — ready for immediate construction.',
    amenities: [
      { tab: 'INFRA',     icon: '🏛', label: 'Gated Entrance with Security Arch'  },
      { tab: 'INFRA',     icon: '🛣', label: '40ft Internal CC Roads'             },
      { tab: 'INFRA',     icon: '💡', label: 'Overhead Electricity Connection'    },
      { tab: 'INFRA',     icon: '💧', label: 'Borewell & Pipeline Water Supply'   },
      { tab: 'INFRA',     icon: '🔒', label: 'Gated Security 24/7'               },
      { tab: 'LIFESTYLE', icon: '🌳', label: 'Tree-Lined Avenues'                },
      { tab: 'LIFESTYLE', icon: '✅', label: '100% Vaastu Compliant'             },
      { tab: 'UTILITIES', icon: '📡', label: 'CCTV Surveillance'                 },
      { tab: 'UTILITIES', icon: '⚡', label: 'LED Street Lights'                 },
    ],
    gallery: [
      { label: 'Trimbak Oaks Phase I — Main Entrance Gate', icon: '🏛' },
      { label: 'Trimbak Oaks Phase I — Internal Roads',     icon: '🛣' },
      { label: 'Trimbak Oaks Phase I — Plot Overview',      icon: '🏞' },
    ],
    videos: [
      { id: '', type: 'youtube', title: 'Trimbak Oaks — Project Overview', subtitle: 'Coming Soon' },
    ],
    distances: [
      { icon: '🏙', name: 'Vijayawada City',    subtitle: 'Business & commercial hub', distance: '5 km'  },
      { icon: '🛣', name: 'NH-16 Highway',      subtitle: 'Direct access',             distance: '2 km'  },
      { icon: '✈', name: 'Vijayawada Airport', subtitle: 'Air connectivity',           distance: '12 km' },
    ],
    mapEmbedUrl: 'https://maps.google.com/maps?q=Penamaluru,Andhra+Pradesh,India&t=k&z=14&ie=UTF8&iwloc=&output=embed',
    mapOpenUrl:  'https://maps.google.com/?q=Penamaluru,Andhra+Pradesh',
    contact: { phone: '+91 99487 09041', whatsapp: '919948709041', email: 'msnraoooo@gmail.com', address: 'Penamaluru, Krishna District, AP', website: 'www.chaturbhujaplots.in' },
  },

  {
    id:          'aparna',
    name:        'Aparna Legacy',
    loc:         'Chevitikallu, Gateway of Amaravati Capital Region',
    fullAddress: 'Chevitikallu Village, Gateway of Amaravati Capital Region, Kanchikacherla Mandal, NTR District, AP',
    accentClass: 'accentBlue',
    heroImage:   '/Aparna_Legacy_Chevitikallu_Home.png',
    available:   16,
    total:       273,
    starting:    'Rs.26L',
    pricing: {
      east:    { base: 12000, dev: 1000, label: 'Rs.12,000 + Rs.1,000 Dev. Charges' },
      west:    { base: 11500, dev: 1000, label: 'Rs.11,500 + Rs.1,000 Dev. Charges' },
      corners: [
        { type: 'North-East Corner', extra: 1000, label: 'Rs.1,000/sq.yd extra' },
        { type: 'Other Corners',     extra: 500,  label: 'Rs.500/sq.yd extra'   },
      ],
      note: 'All prices per sq. yard. Corner charges additional.',
    },
    tag:         'Limited',
    status:      'APCRDA Proposed Layout',
    facings:     { east: 119, west: 138, north: 16 },
    approvals:   ['APCRDA Proposed Layout', '100% Vastu Compliant', 'Clear Title', 'RERA Registered'],
    highlights: [
      'Near ORR — excellent AP Capital connectivity',
      '12 km from Amaravati Capital City',
      'Govt. Proposed Railway Connectivity from Amaravati',
      'Near Amrita Sai, MVR & MIC Engineering Colleges',
      'Close to Nimra Medical College',
      'Near Mulapadu International Cricket Stadium',
      'Proposed Logistic Hub at Paritala',
      'Govt. Proposed Cine Studio near Nandigama',
    ],
    description: 'Premium APCRDA proposed layout plots at Chevitikallu, NTR District — located near the Outer Ring Road with outstanding connectivity to Amaravati. Vastu-compliant plots available. Phase II now open for booking.',
    amenities: [
      { tab: 'INFRA',     icon: '🏛', label: 'Security Arch — Grand Entrance'        },
      { tab: 'INFRA',     icon: '🛣', label: 'BT Roads Throughout Layout'            },
      { tab: 'INFRA',     icon: '💧', label: 'Water Tank & Pipeline Connection'       },
      { tab: 'INFRA',     icon: '📋', label: 'Name & Number Display Board per Plot'  },
      { tab: 'INFRA',     icon: '🔧', label: 'Drainage System'                       },
      { tab: 'INFRA',     icon: '🧱', label: 'Compound Wall'                         },
      { tab: 'LIFESTYLE', icon: '🌳', label: 'Avenue Plantation'                     },
      { tab: 'LIFESTYLE', icon: '🏃', label: 'Walking Track'                         },
      { tab: 'LIFESTYLE', icon: '✅', label: '100% Vastu Compliance'                 },
      { tab: 'LIFESTYLE', icon: '🎡', label: "Children's Play Area"                  },
      { tab: 'LIFESTYLE', icon: '🏞', label: 'Modern Park'                           },
      { tab: 'UTILITIES', icon: '💡', label: 'Electricity Connection'                },
      { tab: 'UTILITIES', icon: '🚰', label: 'Pure Drinking Water'                   },
      { tab: 'UTILITIES', icon: '⚡', label: 'Designed LED Street Lights'            },
    ],
    gallery: [
      { label: 'Grand Entrance Arch',     icon: '🏛' },
      { label: 'BT Road Layout',          icon: '🛣' },
      { label: 'Avenue Plantation',       icon: '🌳' },
      { label: "Children's Play Area",    icon: '🎡' },
      { label: 'Plot Layout — Phase II',  icon: '🏞' },
      { label: 'Modern Park',             icon: '🌸' },
    ],
    videos: [
      { id: 'ccUqV-C1rZQ', type: 'youtube', title: 'Aparna Legacy — Project Overview', subtitle: 'Chevitikallu layout walkthrough' },
    ],
    distances: [
      { icon: '🏛', name: 'Amaravati Capital',    subtitle: 'New AP State Capital',       distance: '12 km'    },
      { icon: '🛣', name: 'Outer Ring Road (ORR)', subtitle: 'Proposed — excellent access', distance: 'Adjacent' },
      { icon: '🎓', name: 'Engineering Colleges', subtitle: 'Amrita Sai, MVR, MIC',       distance: '5 km'     },
      { icon: '🏥', name: 'Nimra Medical College', subtitle: 'Healthcare hub',             distance: '8 km'     },
      { icon: '🏏', name: 'Mulapadu Stadium',     subtitle: 'International Cricket',      distance: '7 km'     },
      { icon: '✈', name: 'Vijayawada Airport',    subtitle: 'Air connectivity',           distance: '18 km'    },
    ],
    mapEmbedUrl: 'https://maps.google.com/maps?q=Chevitikallu,NTR+District,Andhra+Pradesh,India&t=k&z=14&ie=UTF8&iwloc=&output=embed',
    mapOpenUrl:  'https://maps.google.com/?q=Chevitikallu,Kanchikacherla,Andhra+Pradesh',
    contact: { phone: '+91 99487 09041', whatsapp: '919948709041', email: 'msnraoooo@gmail.com', address: 'Chevitikallu Village, Kanchikacherla Mandal, NTR District, AP', website: 'www.chaturbhujaplots.in' },
  },

  {
    id:          'varaha',
    name:        'Varaha Virtue',
    loc:         'Pamarru, Krishna District',
    fullAddress: 'Pamarru Village & Mandal, Krishna District, AP (on NH-16)',
    accentClass: 'accentOrange',
    heroImage:   '/Varaha_Virtue_Pamarru_Home.png',
    available:   20,
    total:       132,
    starting:    'Rs.25L',
    pricing: {
      east:    { base: 15000, dev: 1000, label: 'Rs.15,000 + Rs.1,000 Dev. Charges' },
      west:    { base: 14500, dev: 1000, label: 'Rs.14,500 + Rs.1,000 Dev. Charges' },
      corners: [
        { type: 'North-East Corner', extra: 1000, label: 'Rs.1,000/sq.yd extra' },
        { type: 'Other Corners',     extra: 500,  label: 'Rs.500/sq.yd extra'   },
      ],
      corpus:  { amount: 100, label: 'Rs.100/sq.yd Corpus Fund' },
      note: 'All prices per sq. yard. Corner charges additional.',
    },
    tag:         'Hot',
    status:      'APCRDA Proposed Layout | NH-16 Frontage',
    facings:     { east: 79, west: 53 },
    approvals:   ['APCRDA Proposed Layout', 'NH-16 Frontage', '100% Clear Title', 'Vastu Compliant'],
    highlights: [
      'Directly Adjacent to NH-16 National Highway',
      '15 km from Kathipudi-Ongole Highway',
      '5 km to BEL Company (Defence PSU)',
      '20 km to Bandar Port',
      'Adjacent to Proposed 6-Lane Vijayawada-Machilipatnam Road',
      'Near World-Renowned Bharatanatyam Institution (6 km)',
      'Near Prestigious Engineering Colleges',
      'Ready-to-Build Housing Project',
    ],
    description: 'Strategic investment opportunity on the NH-16 corridor at Pamarru, Krishna District. APCRDA proposed layout with 132 meticulously planned plots — prime NH-16 frontage, near Bandar Port, BEL defence complex and upcoming 6-lane highway. Exceptional appreciation potential.',
    amenities: [
      { tab: 'INFRA',     icon: '🏛', label: 'Security Arch — Grand Entrance'        },
      { tab: 'INFRA',     icon: '🛣', label: 'CC Roads Throughout Layout'            },
      { tab: 'INFRA',     icon: '💧', label: 'Water Tank & Pipeline Connection'       },
      { tab: 'INFRA',     icon: '📋', label: 'Name & Number Display Board'           },
      { tab: 'INFRA',     icon: '🔧', label: 'Drainage System'                       },
      { tab: 'INFRA',     icon: '🧱', label: 'Compound Wall'                         },
      { tab: 'LIFESTYLE', icon: '🌳', label: 'Avenue Plantation on All Road Sides'   },
      { tab: 'LIFESTYLE', icon: '🏃', label: 'Walking Track'                         },
      { tab: 'LIFESTYLE', icon: '✅', label: '100% Vastu Compliance'                 },
      { tab: 'LIFESTYLE', icon: '🎡', label: "Children's Play Area"                  },
      { tab: 'LIFESTYLE', icon: '🏞', label: 'Modern Park — Open Space (0.45 Ac)'   },
      { tab: 'UTILITIES', icon: '💡', label: 'Electricity Connection'                },
      { tab: 'UTILITIES', icon: '🚰', label: 'Pure Drinking Water'                   },
      { tab: 'UTILITIES', icon: '⚡', label: 'Designed LED Street Lights'            },
    ],
    gallery: [
      { label: 'NH-16 Frontage',            icon: '🛣' },
      { label: 'Grand Entrance & Security', icon: '🏛' },
      { label: 'Avenue Plantation',         icon: '🌳' },
      { label: "Children's Play Area",      icon: '🎡' },
      { label: 'Plot Layout Overview',      icon: '🏞' },
      { label: 'Walking Track',             icon: '🏃' },
    ],
    videos: [
      { id: 'TSUf2Pd5LGw', type: 'youtube', title: 'Varaha Virtue — Project Overview', subtitle: 'NH-16 corridor investment opportunity' },
    ],
    distances: [
      { icon: '🛣', name: 'NH-16 National Highway',    subtitle: 'Directly Adjacent',                  distance: '0 km'  },
      { icon: '🏭', name: 'BEL Company (Defence PSU)', subtitle: 'Bharat Electronics Limited',         distance: '5 km'  },
      { icon: '🚢', name: 'Bandar Port',               subtitle: 'Major commercial seaport',           distance: '20 km' },
      { icon: '🎭', name: 'Bharatanatyam Institution', subtitle: 'World-renowned arts centre',         distance: '6 km'  },
      { icon: '🎓', name: 'Engineering Colleges',      subtitle: 'Multiple prestigious institutions',  distance: '8 km'  },
      { icon: '🏙', name: 'Vijayawada',                subtitle: 'Commercial capital of AP',           distance: '25 km' },
    ],
    mapEmbedUrl: 'https://maps.google.com/maps?q=Pamarru,Krishna+District,Andhra+Pradesh,India&t=k&z=14&ie=UTF8&iwloc=&output=embed',
    mapOpenUrl:  'https://maps.google.com/?q=Pamarru,Andhra+Pradesh',
    contact: { phone: '+91 99487 09041', whatsapp: '919948709041', email: 'msnraoooo@gmail.com', address: 'Pamarru Village & Mandal, Krishna District, AP', website: 'www.chaturbhujaplots.in' },
  },
]

export const COMPLETED_PROJECTS = [
  { name: 'Nandana Vihar', loc: 'Kanumuru',  locTe: 'కనుమూరు',  year: '2022', plots: 64 },
  { name: 'County',        loc: 'Edupugallu', locTe: 'ఎదుపుగల్లు', year: '2021', plots: 48 },
  { name: 'Pearl',         loc: 'Kankipadu',  locTe: 'కంకిపాడు',  year: '2020', plots: 36 },
  { name: 'Empire',        loc: 'Penamaluru', locTe: 'పెనమలూరు', year: '2019', plots: 72 },
  { name: 'Pride',         loc: 'Neppalli',   locTe: 'నేప్పల్లి',   year: '2018', plots: 42 },
  { name: 'Prime',         loc: 'Kankipadu',  locTe: 'కంకిపాడు',  year: '2017', plots: 55 },
]

export const COMPANY_CONTACT = {
  phone:            '+91 99487 09041',
  whatsapp:         '919948709041',
  email:            'msnraoooo@gmail.com',
  website:          'www.chaturbhujaplots.in',
  registeredOffice: 'Flat No. 101, Venkat Meadows, Patamata, Vijayawada 520007',
  corporateOffice:  'First Floor, Padmavathi Icon, Panta Kaluva Road, Near Auto Nagar, Vijayawada 520007',
}

